version: "3.0"
services:
  pfaas:
    build:
      context: ./PFaaS
      additional_contexts:
        shared: ./shared
      dockerfile: Dockerfile
    ports:
      - ":9080"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./Simulation
      additional_contexts:
        shared: ./shared
      dockerfile: Dockerfile
    ports:
      - "443:9081"
  scheduler:
    build: ./Scheduler
    ports:
      - ":7080"
  inventory:
    build: ./Inventory
    ports:
      - ":8080"
